ALTER TABLE users ADD COLUMN email VARCHAR(100) UNIQUE NOT NULL;
ALTER TABLE users ADD COLUMN password_hash VARCHAR(255) NOT NULL;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

CREATE INDEX idx_users_email ON users(email);